# Generated by Django 4.2.4 on 2023-08-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_stock_company_name_stock_last_price_stock_market_cap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='previous_close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='year_high',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='year_low',
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
