# Generated by Django 4.2.4 on 2023-08-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_remove_stock_company_name_remove_stock_last_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('previous_close', models.FloatField(blank=True, null=True)),
                ('week52_high', models.FloatField(blank=True, null=True)),
                ('week52_low', models.FloatField(blank=True, null=True)),
                ('ytd_change', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
