# Generated by Django 4.2.4 on 2023-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_stockdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockDetail',
        ),
        migrations.AddField(
            model_name='stock',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
